---
- name: "Create cert output dir"
  file:
    path: "{{ ocp.cluster.certdir }}"
    state: directory
  
- name: "Create ca-config"
  template: 
    src: ca-config.json.j2
    dest: "{{ ocp.cluster.certdir }}/ca-config.json"
    mode: '0644'
 
- name: "Create ca-csr request"
  template: 
    src: ca-csr.json.j2
    dest: "{{ ocp.cluster.certdir }}/ca-csr.json"
    mode: '0644'
  
- name: "Generate ca.crt"
  shell: "cfssl gencert -initca ca-csr.json | cfssljson -bare ca"
  environment:
    PATH: "{{ cfssl.bindir | realpath }}" 
  args:
    chdir: "{{ ocp.cluster.certdir }}"
  
- name: "Create mongodb-csr request"
  template: 
    src: mongodb-csr.json.j2
    dest: "{{ ocp.cluster.certdir }}/mongodb-csr.json"
    mode: '0644'

- name: "Create hosts list"
  set_fact:
    hosts_list:
      - localhost
      - localhost.localdomain
      - 127.0.0.1
      - mongo-cluster01.apps.cluster01.rheventdemo.com
      - mongo-cluster02.apps.cluster02.rheventdemo.com
      - mongo-cluster03.apps.cluster03.rheventdemo.com
      - mongodb
      - mongodb.{{ namespace | default('federated-mongo') }}
      - mongodb.{{ namespace | default('federated-mongo') }}.svc.cluster.local

- name: "Generate mongodb crt"
  shell: "cfssl gencert -ca=ca.pem -ca-key=ca-key.pem -config=ca-config.json -hostname={{ hosts_list | join(',') }} -profile={{ ca_profile }} mongodb-csr.json | cfssljson -bare mongodb"
  environment:
    PATH: "{{ cfssl.bindir | realpath }}" 
  args:
    chdir: "{{ ocp.cluster.certdir }}"
  
  
- name: "Concatenate mongo pem"
  shell: "cat mongodb-key.pem mongodb.pem > mongo.pem"
  args:
    chdir: "{{ ocp.cluster.certdir }}"

