---
- name: "Prepare environment for federated MongoDB deployment"
  hosts: localhost
  gather_facts: no

  vars:
    var_demofolder_name: fed-ocp-demo
    var_certdir_name: certs
    var_mongodb_pem_data_path: "~/{{ var_demofolder_name }}/{{ var_certdir_name }}/mongo.pem"
    var_ca_pem_data_path: "~/{{ var_demofolder_name }}/{{ var_certdir_name }}/ca.pem"
    var_mongodb_pem_data: "{{ lookup('file', var_mongodb_pem_data_path) | b64encode }}"
    var_ca_pem_data: "{{ lookup('file', var_ca_pem_data_path) | b64encode }}"

  tasks:
    - name: show var_mongodb_pem_data Content
      debug:
        var: var_mongodb_pem_data

    - name: show var_ca_pem_data Content
      debug:
        var: var_ca_pem_data
