
---
- name: Create secret with admin/access credentials
  shell: "export KUBECONFIG={{ kube_concat_path }}; oc --context={{ var_kubefed_operator }} -n {{ var_obj_spec_targetnamespace }} create -f ~/{{ var_demofolder_name }}/{{ var_mongofed_configfolder_name }}/01-mongo-federated-secret.yaml"
  #ignore_errors: yes

- name: Create service
  shell: "export KUBECONFIG={{ kube_concat_path }}; oc --context={{ var_kubefed_operator }} -n {{ var_obj_spec_targetnamespace }} create -f ~/{{ var_demofolder_name }}/{{ var_mongofed_configfolder_name }}/02-mongo-federated-service.yaml"
  #ignore_errors: yes

- name: Create persistent volume claim
  shell: "export KUBECONFIG={{ kube_concat_path }}; oc --context={{ var_kubefed_operator }} -n {{ var_obj_spec_targetnamespace }} create -f ~/{{ var_demofolder_name }}/{{ var_mongofed_configfolder_name }}/03-mongo-federated-pvc.yaml"
  #ignore_errors: yes

- name: Create deployment
  shell: "export KUBECONFIG={{ kube_concat_path }}; oc --context={{ var_kubefed_operator }} -n {{ var_obj_spec_targetnamespace }} create -f ~/{{ var_demofolder_name }}/{{ var_mongofed_configfolder_name }}/04-mongo-federated-deployment-rs.yaml"
  #ignore_errors: yes

- name: Create routes
  shell: "export KUBECONFIG={{ kube_concat_path }}; oc --context={{ item.name }} -n {{ var_obj_spec_targetnamespace }} create route passthrough mongo --service={{ var_mongofed_service }} --port={{ var_mongo_db_external_port }} --hostname=mongo-{{ item.name }}.apps.{{ item.name }}.rheventdemo.com"
  loop: "{{ var_cluster_info }}"
  register: fedroute
