---
- name: Create mongofed config folder
  file:
    path: "~/{{ var_demofolder_name }}/{{ var_mongofed_configfolder_name }}"
    state: directory

- name: Backup kubeconfig files
  copy:
    src: "~/{{ var_demofolder_name }}/{{ item.name }}/auth/kubeconfig"
    dest: "~/{{ var_demofolder_name }}/{{ item.name }}/auth/bkp_kubeconfig"
  loop: "{{ var_cluster_info }}"

- name: Modify kubeconfig files
  replace:
    path: "~/{{ var_demofolder_name }}/{{ item.name }}/auth/kubeconfig"
    regexp: 'admin'
    replace: "{{ item.name }}"
  loop: "{{ var_cluster_info }}"

- name: Concatenate kubeconfig paths step1
  set_fact:
    kube_path_1: "{{ kube_path_1 | default() }}:~/{{ var_demofolder_name }}/{{ item.name }}/auth/kubeconfig"
  loop: "{{ var_cluster_info }}"

- name: Remove kubeconfig paths step1 first separator
  set_fact:
    kube_path_1: "{{ 'kube_path_1' | regex_replace('^:(.*)$', '\\1') }}"

- name: Show kube_path_1 content
  debug:
    var: kube_path_1
