---
var_cluster_info:
  - { name: cluster01, region: eu-west-3, deploy: true }
  - { name: cluster02, region: eu-central-1, deploy: true }
  - { name: cluster03, region: eu-west-1, deploy: true }

var_cluster_list:
  - cluster01
  - cluster02
  - cluster03

var_demofolder_name: fed-ocp-demo
var_certdir_name: certs
var_mongofed_configfolder_name: mongofed
var_kubefed_operator: cluster01

install_state: present

var_kubefed_scope: Cluster
var_kubefed_scope: Namespaced
#var_mongofed_namespace: mongo-namespace

var_obj_kind: KubeFed
var_obj_metadata_name: kubefed-resource
var_obj_spec_targetnamespace: "{{ var_csc_spec_targetnamespace }}"


var_fed_obj_list:
  - namespaces
  - deployments.apps
  - ingresses.extensions
  - secrets
  - serviceaccounts
  - services
  - persistentvolumeclaims
  - configmaps

var_mongodb_pem_data_path: "~/{{ var_demofolder_name }}/{{ var_certdir_name }}/mongo.pem"
var_ca_pem_data_path: "~/{{ var_demofolder_name }}/{{ var_certdir_name }}/ca.pem"
var_mongodb_pem_data: "{{ lookup('file', var_mongodb_pem_data_path) | b64encode }}"
var_ca_pem_data: "{{ lookup('file', var_ca_pem_data_path) | b64encode }}"

var_mongo_db_external_port: 27017
var_mongo_db_internal_port: 27017

var_mongofed_service: mongodb
var_mongofed_namespace: "{{ var_obj_spec_targetnamespace }}"

var_primary_node: mongo-cluster01.apps.cluster01.rheventdemo.com:443
var_replica_members: mongo-cluster01.apps.cluster01.rheventdemo.com:443,mongo-cluster02.apps.cluster02.rheventdemo.com:443,mongo-cluster03.apps.cluster03.rheventdemo.com:443
