---
- name: "Create k8s namespace {{ var_csc_spec_targetnamespace }}"
  k8s:
    kubeconfig: "{{ var_kubeconfig_path }}"
    state: "{{ install_state }}"
    name: "{{ var_csc_spec_targetnamespace }}"
    api_version: v1
    kind: Namespace

- name: Create CatalogSourceConfig {{ var_csc_metadata_name }}
  k8s:
    kubeconfig: "{{ var_kubeconfig_path }}"
    state: "{{ install_state }}"
    definition:
      apiVersion: operators.coreos.com/v1
      kind: "{{ var_csc_kind }}"
      metadata:
        name: "{{ var_csc_metadata_name }}"
        namespace: "{{ var_csc_metadata_namespace }}"
      spec:
        targetNamespace: "{{ var_csc_spec_targetnamespace }}"
        packages: "{{ var_csc_spec_packages }}"

- name: Create OperatorGroup {{ var_og_metadata_name }}
  k8s:
    kubeconfig: "{{ var_kubeconfig_path }}"
    state: "{{ install_state }}"
    definition:
      apiVersion: operators.coreos.com/v1
      kind: "{{ var_og_kind }}"
      metadata:
        generation: 2
        name: "{{ var_og_metadata_name }}"
        namespace: "{{ var_og_metadata_namespace }}"
      spec:
        targetNamespaces:
          - "{{var_og_spec_namespace }}"

- name: Create Subscription {{ var_sub_metadata_name }}
  k8s:
    kubeconfig: "{{ var_kubeconfig_path }}"
    state: "{{ install_state }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: "{{ var_sub_kind }}"
      metadata:
        name: "{{ var_sub_metadata_name }}"
        namespace: "{{ var_sub_metadata_namespace }}"
      spec:
        channel: "{{ var_sub_spec_channel }}"
        name: "{{ var_sub_spec_name }}"
        source: "{{ var_sub_spec_source }}"
        sourceNamespace: "{{ var_sub_spec_sourcenamespace }}"
        startingCSV: "{{ var_sub_spec_startingcsv }}"
        installPlanApproval: "{{ var_sub_spec_installplanapproval }}"

- name: Wait for kubefed operator to be available
  pause:
    seconds: 30

- name: Enable the Kubefed Controller Manager
  k8s:
    kubeconfig: "{{ var_kubeconfig_concat_path }}"
    namespace: "{{ var_obj_spec_targetnamespace }}"
    context: "{{ var_kubefed_operator }}"
    state: "{{ install_state }}"
    definition:
      apiVersion: operator.kubefed.io/v1alpha1
      kind: "{{ var_obj_kind }}"
      metadata:
        name: "{{ var_obj_metadata_name }}"
      spec:
        scope: "{{ var_kubefed_scope }}"

- name: Enable federated ressources
  command: "./kubefedctl enable {{ item }}"
  args:
    chdir: "{{ '~/bin' | expanduser }}"
  environment:
    KUBECONFIG: "{{ var_kubeconfig_concat_path }}"
  loop: "{{ var_fed_obj_list }}"
  register: fedobj

- name: Wait for federated ressources to be available
  pause:
    seconds: 30

- name: Federate OpenShift clusters
  command: "./kubefedctl join {{ item.name }} --cluster-context {{  item.name }} --host-cluster-context {{ var_kubefed_operator }} --v=2"
  args:
    chdir: "{{ '~/bin' | expanduser }}"
  environment:
    KUBECONFIG: "{{ var_kubeconfig_concat_path }}"
  loop: "{{ var_cluster_info }}"
  register: fedocp
