---
- name: "Create or delete k8s namespace {{ var_csc_spec_targetnamespace }}"
  k8s:
    kubeconfig: "{{ var_kubeconfig_path }}"
    state: "{{ install_state }}"
    name: "{{ var_csc_spec_targetnamespace }}"
    api_version: v1
    kind: Namespace

- name: Create CatalogSourceConfig {{ var_csc_metadata_name }}
  k8s:
    kubeconfig: "{{ var_kubeconfig_path }}"
    state: "{{ install_state }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: "{{ var_csc_kind }}"
      metadata:
        name: "{{ var_csc_metadata_name }}"
        namespace: "{{ var_csc_metadata_namespace }}"
      spec:
        targetNamespace: "{{ var_csc_spec_targetnamespace }}"
        packages: "{{ var_csc_spec_packages }}"

- name: Create OperatorGroup {{ var_og_metadata_name }}
  k8s:
    kubeconfig: "{{ var_kubeconfig_path }}"
    state: "{{ install_state }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: "{{ var_og_kind }}"
      metadata:
        generation: 2
        name: "{{ var_og_metadata_name }}"
        namespace: "{{ var_og_metadata_namespace }}"
      spec:
        targetNamespaces:
          - "{{var_og_spec_namespace }}"

- name: Create Subscription {{ var_sub_metadata_name }}
  k8s:
    kubeconfig: "{{ var_kubeconfig_path }}"
    state: "{{ install_state }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: "{{ var_sub_kind }}"
      metadata:
        name: "{{ var_sub_metadata_name }}"
        namespace: "{{ var_sub_metadata_namespace }}"
      spec:
        channel: "{{ var_sub_spec_channel }}"
        name: "{{ var_sub_spec_name }}"
        source: "{{ var_sub_spec_source }}"
        sourceNamespace: "{{ var_sub_spec_sourcenamespace }}"
        startingCSV: "{{ var_sub_spec_startingcsv }}"
        installPlanApproval: "{{ var_sub_spec_installplanapproval }}"
