---
- name: "Federate namespace cluster"
  hosts: localhost
  gather_facts: no

  vars:
    namespace: ansible-k8s-testing
    install_state: present
    cluster_context:
      - cluster12

  tasks:
    - name: "check federated namespace {{ namespace }} available"
      shell: "oc get csv -n {{ namespace }} | egrep federation"
      register: federated_check
      failed_when: federated_check.rc == 1

#      command: "{{ bindir }}/kubefedctl join {{ item }} --host-cluster-context {{ host_cluster_context | default(cluster_context[0]) }} --kubefed-namespace={{ namespace }}"

    - name: "Join all cluster with context"
      command: "{{ bindir }}/kubefedctl join {{ item }} --host-cluster-context {{ host_cluster_context | default(cluster_context[0]) }} --add-to-registry --v=2 --federation-namespace={{ namespace }}"
      register: join_check
      failed_when: join_check.rc == 1
      with_items:
       - "{{ cluster_context }}"
