---
- name: Create {{ var_kubeconfigfolder_name }} config folder
  file:
    path: "~/{{ var_demofolder_name }}/{{ var_kubeconfigfolder_name }}"
    state: directory

- name: Backup kubeconfig files
  copy:
    src: "~/{{ var_demofolder_name }}/{{ item.name }}/auth/kubeconfig"
    dest: "~/{{ var_demofolder_name }}/{{ item.name }}/auth/bkp_kubeconfig"
  loop: "{{ var_cluster_info }}"

- name: Modify kubeconfig files
  replace:
    path: "~/{{ var_demofolder_name }}/{{ item.name }}/auth/kubeconfig"
    regexp: 'admin'
    replace: "{{ item.name }}"
  loop: "{{ var_cluster_info }}"

- name: Concatenate kubeconfig paths
  set_fact:
    kube_concat_path: "{{ kube_concat_path | default() }}:~/{{ var_demofolder_name }}/{{ item.name }}/auth/kubeconfig"
    kube_concat_name: "{{ kube_concat_name | default('aws') }}-{{ item.name }}"
  loop: "{{ var_cluster_info }}"

- name: Remove kubeconfig concat path first separator
  set_fact:
    kube_concat_path: "{{ kube_concat_path | regex_replace('^:(.*)$', '\\1') }}"

- name: Flatten kube concat path
  shell: "export KUBECONFIG={{ kube_concat_path }}; oc config view --flatten > {{ kube_concat_name }}"
  args:
    chdir: "~/{{ var_demofolder_name }}/{{ var_kubeconfigfolder_name }}"
  register: occfgv_flatten

- name: Copy {{ kube_concat_name }} to {{ var_kube_concat_name }}
  copy:
    src: "~/{{ var_demofolder_name }}/{{ var_kubeconfigfolder_name }}/{{ kube_concat_name }}"
    dest: "~/{{ var_demofolder_name }}/{{ var_kubeconfigfolder_name }}/{{ var_kube_concat_name }}"
