---
- name: Create config backup folders
  file:
    path: "./{{ item.name }}/bkp"
    state: directory
  loop: "{{ var_cluster_info }}"

- name: Backup configuration files before deployment
  copy:
    src: "./{{ item.name }}/{{ var_installconfig }}"
    dest: "./{{ item.name }}/bkp"
  loop: "{{ var_cluster_info }}"

- name: Backup state files before deployment
  copy:
    src: "./{{ item.name }}/{{ var_openshiftinstallstate }}"
    dest: "./{{ item.name }}/bkp"
  loop: "{{ var_cluster_info }}"

- name: Deploy OpenShift cluster(s)
  shell: "./openshift-install create cluster --log-level=debug"
  args:
    chdir: "./{{ item.name }}/"
  loop: "{{ var_cluster_info }}"
  when: item.deploy == true
  register: cluster_deployment
  async: 1800
  poll: 0


- name: Wait for OpenShift cluster(s) deployment result(s)
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: cluster_deployment_status
  until: cluster_deployment_status.finished
  retries: 20
  delay: 30
  loop: "{{ cluster_deployment.results }}"
