---
var_csc_kind: CatalogSourceConfig
var_csc_metadata_name: namespaced-federation
var_csc_metadata_namespace: openshift-marketplace
var_csc_spec_targetnamespace: fed-mongo-namespace
var_csc_spec_packages: kf
var_csc_spec_csdisplayname: Community Operators
var_csc_spec_cspublisher: Community

var_og_kind: OperatorGroup
var_og_metadata_name: "{{ var_csc_metadata_name }}"
var_og_metadata_namespace: "{{ var_csc_spec_targetnamespace }}"
var_og_spec_namespace: "{{ var_csc_spec_targetnamespace }}"

var_sub_kind: Subscription
var_sub_metadata_name: kubefed-subscription
var_sub_metadata_namespace: "{{ var_csc_spec_targetnamespace }}"
var_sub_spec_channel: alpha
var_sub_spec_name: "{{ var_csc_spec_packages }}"
var_sub_spec_source: "{{ var_csc_metadata_name }}"
var_sub_spec_sourcenamespace: "{{ var_csc_spec_targetnamespace }}"
var_sub_spec_startingcsv: kubefed-operator:v0.1.0-rc3
var_sub_spec_installplanapproval: Automatic

var_demofolder_name: fed-ocp-demo
var_kubefed_operator: cluster01
var_kubeconfig_path: "~/{{ var_demofolder_name }}/{{ var_kubefed_operator }}/auth/kubeconfig"

install_state: present
